prometheus:
  prometheusSpec:
    retention: "7d"
    resources:
      requests:
        memory: 512Mi
grafana:
  enabled: true
  adminUser: admin
  adminPassword: "${GRAFANA_ADMIN_PASSWORD}" # inject from a k8s secret or use sealed-secrets
  ingress:
    enabled: true
    hosts:
      - grafana.example.com
  persistence:
    enabled: true
    size: 10Gi

